In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('matches.csv').dropna()
print(df.shape)
df

(87504, 31)

,Team1,Team2,Team1Score,Team1FGM,Team1FGA,Team1FGM3,Team1FGA3,Team1FTM,Team1FTA,Team1OR,...,Team2FTM,Team2FTA,Team2OR,Team2DR,Team2Ast,Team2TO,Team2Stl,Team2Blk,Team2PF,Win
0,1421.0,1411.0,70.857116,24.835506,56.434951,6.414692,18.565785,14.771413,20.665618,10.963364,...,15.710680,24.005781,11.705997,24.357526,12.123150,15.493189,6.690597,3.153172,18.467932,1.0
1,1436.0,1112.0,69.855278,24.480532,53.811272,5.963383,16.755914,14.930832,21.279172,10.879975,...,16.325509,22.252281,11.423081,25.023546,14.801796,12.812651,6.345888,3.615896,16.994665,0.0
2,1272.0,1113.0,74.907473,26.294729,58.543421,6.600664,19.351685,15.717352,23.277168,12.826705,...,14.981736,21.478844,10.385801,23.829096,14.160912,13.034717,6.020814,3.427225,18.325749,0.0
3,1166.0,1141.0,73.853850,25.786073,55.304019,8.163962,21.624711,14.117741,19.608092,9.641230,...,14.649615,20.785129,11.083005,21.987842,11.666412,14.050869,6.743972,2.753055,20.340310,0.0
4,1143.0,1301.0,70.866565,25.397341,56.385076,5.714419,16.266095,14.357464,20.499749,10.694625,...,14.982759,21.068132,11.159053,24.149595,14.311193,12.886297,6.121473,4.054906,17.563236,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87499,1222.0,1153.0,71.771016,25.204507,58.794377,7.545320,21.726073,13.816683,19.867904,12.084937,...,13.732238,20.207679,13.148627,24.008656,13.732706,11.917886,6.749893,4.619880,17.345175,0.0
87500,1426.0,1209.0,72.019186,24.930561,56.479932,6.562952,19.484382,15.595111,22.385911,11.769553,...,12.904338,18.946975,10.474991,22.818635,12.310418,12.914212,7.224662,3.955291,18.208575,0.0
87501,1276.0,1277.0,68.475813,24.348245,54.331513,7.466010,21.268194,12.313312,16.942697,9.690189,...,14.332614,19.902945,11.425292,25.795765,16.477806,13.375807,6.056469,4.143110,18.716245,0.0
87502,1387.0,1382.0,63.494207,22.231210,51.858981,5.762812,17.227175,13.268976,19.569258,9.381374,...,14.830486,20.661597,11.635670,23.423994,13.461296,13.571104,6.254446,3.454038,18.901495,1.0
87503,1217.0,1463.0,68.814578,23.732631,53.368668,6.463489,18.256672,14.885827,20.376484,10.148701,...,14.754860,20.986298,10.472433,24.317282,13.717283,14.313944,6.305621,3.535035,18.285989,0.0

In [3]:
columns  = list(df.columns.copy())
columns.remove('Team1')
columns.remove('Team2')
columns.remove('Win')
columns

['Team1Score',
 'Team1FGM',
 'Team1FGA',
 'Team1FGM3',
 'Team1FGA3',
 'Team1FTM',
 'Team1FTA',
 'Team1OR',
 'Team1DR',
 'Team1Ast',
 'Team1TO',
 'Team1Stl',
 'Team1Blk',
 'Team1PF',
 'Team2Score',
 'Team2FGM',
 'Team2FGA',
 'Team2FGM3',
 'Team2FGA3',
 'Team2FTM',
 'Team2FTA',
 'Team2OR',
 'Team2DR',
 'Team2Ast',
 'Team2TO',
 'Team2Stl',
 'Team2Blk',
 'Team2PF']

In [4]:
common = [c.replace('Team1', '') for c in columns if c.startswith('Team1')]
common

['Score',
 'FGM',
 'FGA',
 'FGM3',
 'FGA3',
 'FTM',
 'FTA',
 'OR',
 'DR',
 'Ast',
 'TO',
 'Stl',
 'Blk',
 'PF']

In [5]:
for c in common:
    df[c] = df[f'Team1{c}'] - df[f'Team2{c}']

df

,Team1,Team2,Team1Score,Team1FGM,Team1FGA,Team1FGM3,Team1FGA3,Team1FTM,Team1FTA,Team1OR,...,FGA3,FTM,FTA,OR,DR,Ast,TO,Stl,Blk,PF
0,1421.0,1411.0,70.857116,24.835506,56.434951,6.414692,18.565785,14.771413,20.665618,10.963364,...,0.881936,-0.939267,-3.340163,-0.742632,-0.677068,1.729802,-0.756330,0.648304,0.664272,-0.607997
1,1436.0,1112.0,69.855278,24.480532,53.811272,5.963383,16.755914,14.930832,21.279172,10.879975,...,-0.800801,-1.394677,-0.973109,-0.543107,-0.034545,-1.456050,0.284372,-0.239265,0.017690,0.474607
2,1272.0,1113.0,74.907473,26.294729,58.543421,6.600664,19.351685,15.717352,23.277168,12.826705,...,-0.985461,0.735616,1.798324,2.440904,1.049760,0.727133,0.345803,1.952151,1.948516,0.417965
3,1166.0,1141.0,73.853850,25.786073,55.304019,8.163962,21.624711,14.117741,19.608092,9.641230,...,-0.370801,-0.531874,-1.177037,-1.441776,2.729467,3.557566,-1.665977,-0.634785,0.228078,-2.998282
4,1143.0,1301.0,70.866565,25.397341,56.385076,5.714419,16.266095,14.357464,20.499749,10.694625,...,-2.476242,-0.625295,-0.568383,-0.464428,0.210106,-0.569521,-0.228914,-0.782866,-0.714186,0.253653
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87499,1222.0,1153.0,71.771016,25.204507,58.794377,7.545320,21.726073,13.816683,19.867904,12.084937,...,2.131097,0.084445,-0.339775,-1.063689,0.002905,-0.942806,0.544570,0.348851,-0.550860,1.729235
87500,1426.0,1209.0,72.019186,24.930561,56.479932,6.562952,19.484382,15.595111,22.385911,11.769553,...,1.012062,2.690773,3.438936,1.294562,2.504410,1.159486,2.751592,-0.641121,-0.949928,1.708144
87501,1276.0,1277.0,68.475813,24.348245,54.331513,7.466010,21.268194,12.313312,16.942697,9.690189,...,4.009131,-2.019302,-2.960247,-1.735104,-2.959495,-2.890660,-1.841887,-0.177482,-0.894682,-3.101508
87502,1387.0,1382.0,63.494207,22.231210,51.858981,5.762812,17.227175,13.268976,19.569258,9.381374,...,-1.287803,-1.561510,-1.092339,-2.254295,0.332172,-0.628147,-0.784609,-0.319886,-0.319017,-1.118570
87503,1217.0,1463.0,68.814578,23.732631,53.368668,6.463489,18.256672,14.885827,20.376484,10.148701,...,1.065594,0.130967,-0.609815,-0.323731,-0.615854,-0.561652,0.463602,0.438711,0.362869,-0.617451

In [6]:
df = df.drop(columns, axis=1)
df.shape

(87504, 17)

In [7]:
df2 = pd.read_csv('matches.csv').dropna()
for name in common:
    df2[name] = df[name]

In [8]:
print(df2.shape)
dfs.head()

(87504, 45)

,Team1,Team2,Win,Score,FGM,FGA,FGM3,FGA3,FTM,FTA,OR,DR,Ast,TO,Stl,Blk,PF
0,1421.0,1411.0,1.0,1.994712,1.118415,1.377522,0.697148,0.881936,-0.939267,-3.340163,-0.742632,-0.677068,1.729802,-0.756330,0.648304,0.664272,-0.607997
1,1436.0,1112.0,0.0,-6.405532,-2.235668,-3.294793,-0.539518,-0.800801,-1.394677,-0.973109,-0.543107,-0.034545,-1.456050,0.284372,-0.239265,0.017690,0.474607
2,1272.0,1113.0,0.0,3.853308,1.852635,3.768736,-0.587577,-0.985461,0.735616,1.798324,2.440904,1.049760,0.727133,0.345803,1.952151,1.948516,0.417965
3,1166.0,1141.0,0.0,4.173797,2.105784,-0.446416,0.494102,-0.370801,-0.531874,-1.177037,-1.441776,2.729467,3.557566,-1.665977,-0.634785,0.228078,-2.998282
4,1143.0,1301.0,1.0,-2.580861,-0.504182,-0.052969,-0.947201,-2.476242,-0.625295,-0.568383,-0.464428,0.210106,-0.569521,-0.228914,-0.782866,-0.714186,0.253653

In [9]:
df2.to_csv('delta_matches.csv')